app/routes/set_theme.py
from flask import Blueprint, redirect, request, session, url_for
from settings import Settings
from utils.log import Log

set_theme_blueprint = Blueprint("set_theme", __name__)


@set_theme_blueprint.route("/set_theme/<theme>")
def set_theme(theme):
    """
    Set the theme for the application.

    Parameters:
        theme (str): The theme name to set for the application.

    Returns:
        str: Redirect to the previous page or home.
    """
    if theme in Settings.THEMES:
        session["theme"] = theme
        Log.info(f"Theme set to: {theme}")
    else:
        Log.warning(f"Theme not supported: {theme}")

    # Redirect back to the page the user came from, or home if no referrer
    return redirect(request.referrer or url_for("index"))

app/templates/components/categoryContainer.html
{% macro categoryContainer(translations, category) %}

<div class="dropdown">
    <div
        tabindex="0"
        role="button"
        class="btn w-full md:w-fit text-base-content"
    >
        {{ category }}
    </div>
    <ul
        tabindex="0"
        class="dropdown-content menu bg-base-100 rounded-box z-1 w-72 p-2 shadow-sm"
    >
        <li>
            <a onclick="location = '/'">{{ translations.categories.all }}</a>
        </li>
        <li>
            <a onclick="location = '/category/Apps'"
                >{{ translations.categories.apps }}</a
            >
        </li>
        <li>
            <a onclick="location = '/category/Art'"
                >{{ translations.categories.art }}</a
            >
        </li>
        <li>
            <a onclick="location = '/category/Books'"
                >{{ translations.categories.books }}</a
            >
        </li>
        <li>
            <a onclick="location = '/category/Business'"
                >{{ translations.categories.business }}</a
            >
        </li>
        <li>
            <a onclick="location = '/category/Code'"
                >{{ translations.categories.code }}</a
            >
        </li>
        <li>
            <a onclick="location = '/category/Education'"
                >{{ translations.categories.education }}</a
            >
        </li>
        <li>
            <a onclick="location = '/category/Finance'"
                >{{ translations.categories.finance }}</a
            >
        </li>
        <li>
            <a onclick="location = '/category/Foods'"
                >{{ translations.categories.foods }}</a
            >
        </li>
        <li>
            <a onclick="location = '/category/Games'"
                >{{ translations.categories.games }}</a
            >
        </li>
        <li>
            <a onclick="location = '/category/Health'"
                >{{ translations.categories.health }}</a
            >
        </li>
        <li>
            <a onclick="location = '/category/History'"
                >{{ translations.categories.history }}</a
            >
        </li>
        <li>
            <a onclick="location = '/category/Movies'"
                >{{ translations.categories.movies }}</a
            >
        </li>
        <li>
            <a onclick="location = '/category/Music'"
                >{{ translations.categories.music }}</a
            >
        </li>
        <li>
            <a onclick="location = '/category/Nature'"
                >{{ translations.categories.nature }}</a
            >
        </li>
        <li>
            <a onclick="location = '/category/Science'"
                >{{ translations.categories.science }}</a
            >
        </li>
        <li>
            <a onclick="location = '/category/Series'"
                >{{ translations.categories.series }}</a
            >
        </li>
        <li>
            <a onclick="location = '/category/Sports'"
                >{{ translations.categories.sports }}</a
            >
        </li>
        <li>
            <a onclick="location = '/category/Technology'"
                >{{ translations.categories.technology }}</a
            >
        </li>
        <li>
            <a onclick="location = '/category/Travel'"
                >{{ translations.categories.travel }}</a
            >
        </li>
        <li>
            <a onclick="location = '/category/Web'"
                >{{ translations.categories.web }}</a
            >
        </li>
        <li>
            <a onclick="location = '/category/Other'"
                >{{ translations.categories.other }}</a
            >
        </li>
    </ul>
</div>
{% endmacro %}

app/templates/components/changeTheme.html
<div class="absolute right-2 top-2">
    <div class="dropdown dropdown-end">
        <button
            tabindex="0"
            class="btn btn-ghost btn-circle"
            aria-label="Change theme"
        >
            <i class="ti ti-palette"></i>
        </button>
        <ul
            tabindex="0"
            class="dropdown-content menu bg-base-100 rounded-box z-[1] w-52 p-2 shadow max-h-96 overflow-y-auto"
            role="menu"
        >
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='light') }}"
                    role="menuitem"
                    >☀️ Light</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='dark') }}"
                    role="menuitem"
                    >🌙 Dark</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='cupcake') }}"
                    role="menuitem"
                    >🧁 Cupcake</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='bumblebee') }}"
                    role="menuitem"
                    >🐝 Bumblebee</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='emerald') }}"
                    role="menuitem"
                    >💚 Emerald</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='corporate') }}"
                    role="menuitem"
                    >🏢 Corporate</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='synthwave') }}"
                    role="menuitem"
                    >🌊 Synthwave</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='retro') }}"
                    role="menuitem"
                    >📺 Retro</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='cyberpunk') }}"
                    role="menuitem"
                    >🤖 Cyberpunk</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='valentine') }}"
                    role="menuitem"
                    >💝 Valentine</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='halloween') }}"
                    role="menuitem"
                    >🎃 Halloween</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='garden') }}"
                    role="menuitem"
                    >🌻 Garden</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='forest') }}"
                    role="menuitem"
                    >🌲 Forest</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='aqua') }}"
                    role="menuitem"
                    >💧 Aqua</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='lofi') }}"
                    role="menuitem"
                    >🎵 Lo-fi</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='pastel') }}"
                    role="menuitem"
                    >🎨 Pastel</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='fantasy') }}"
                    role="menuitem"
                    >🦄 Fantasy</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='wireframe') }}"
                    role="menuitem"
                    >📐 Wireframe</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='black') }}"
                    role="menuitem"
                    >⚫ Black</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='luxury') }}"
                    role="menuitem"
                    >💎 Luxury</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='dracula') }}"
                    role="menuitem"
                    >🧛 Dracula</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='cmyk') }}"
                    role="menuitem"
                    >🖨️ CMYK</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='autumn') }}"
                    role="menuitem"
                    >🍂 Autumn</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='business') }}"
                    role="menuitem"
                    >💼 Business</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='acid') }}"
                    role="menuitem"
                    >🟢 Acid</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='lemonade') }}"
                    role="menuitem"
                    >🍋 Lemonade</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='night') }}"
                    role="menuitem"
                    >🌃 Night</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='coffee') }}"
                    role="menuitem"
                    >☕ Coffee</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='winter') }}"
                    role="menuitem"
                    >❄️ Winter</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='dim') }}"
                    role="menuitem"
                    >🔅 Dim</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='nord') }}"
                    role="menuitem"
                    >🗻 Nord</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='sunset') }}"
                    role="menuitem"
                    >🌅 Sunset</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='caramellatte') }}"
                    role="menuitem"
                    >🍯 Caramel Latte</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='abyss') }}"
                    role="menuitem"
                    >🖤 Abyss</a
                >
            </li>
            <li>
                <a
                    href="{{ url_for('set_theme.set_theme', theme='silk') }}"
                    role="menuitem"
                    >🎀 Silk</a
                >
            </li>
        </ul>
    </div>
</div>

app/templates/components/flash.html
{% macro flash() %}

<link
    rel="stylesheet"
    href="{{ url_for('static', filename='css/flash.css') }}"
/>

<div id="flashContainer" class="fixed text-center select-none z-50">
    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %}
    <div
        role="alert"
        class="alert shadow-md {% if category == 'success' %}alert-success{% else %}alert-error{% endif %} alert-soft"
    >
        {% if category == 'success' %}<i
            class="ti ti-circle-check-filled text-xl"
        ></i
        >{% else %} <i class="ti ti-circle-x-filled text-xl"></i>{% endif %}
        <span>{{ message }}</span>
    </div>
    {% endfor %} {% endif %} {% endwith %}
</div>
{% endmacro %}

app/templates/components/navbar.html
<div
    class="w-11/12 lg:w-10/12 xl:w-9/12 2xl:w-8/12 flex items-center justify-between mt-8 lg:mt-4 text-2xl font-medium select-none mx-auto"
>
    <a href="/" class="duration-150">
        <img
            src="https://raw.githubusercontent.com/DogukanUrker/flaskBlog/main/images/Icon180.ico"
            class="rounded w-14 hover:scale-110 duration-150 shadow"
        />
    </a>

    <div class="hidden md:block">
        <input
            type="text"
            id="searchInput"
            autocomplete="off"
            placeholder="{{translations.searchBar.placeholder}}"
            class="input input-bordered w-64"
        />
        <button onclick="search()" class="btn btn-neutral">
            <i class="ti ti-search text-2xl"></i>
        </button>
    </div>

    <div class="flex items-center justify-center gap-4 font-medium select-none">
        <div class="block md:hidden">
            <a href="/search_bar"><i class="ti ti-search text-2xl"></i></a>
        </div>

        {% if session["username"] %}
        <a href="/user/{{ session['username'].lower() }}">
            <div>
                <img
                    class="block w-7 h-7"
                    src="{{ get_profile_picture(session['username']) }}"
                />
            </div>
        </a>

        <a href="/create_post" class="text-center">
            <button class="hover:text-rose-500 duration-150">
                <i class="ti ti-pencil-plus text-2xl"></i>
            </button>
        </a>

        <a
            href="/logout"
            title="logout"
            class="hover:text-rose-500 duration-150"
        >
            <i class="ti ti-logout text-2xl"></i>
        </a>

        {% elif hideLogin %} {% if is_registration %}
        <a href="/signup">
            <button class="hover:text-rose-500 duration-150">
                <i class="ti ti-user-plus text-2xl"></i>
            </button>
        </a>
        {% endif %} {% elif hideSignUp %} {% if is_login %}
        <a href="/login/redirect=&">
            <button class="hover:text-rose-500 duration-150">
                <i class="ti ti-login text-2xl"></i>
            </button>
        </a>
        {% endif %} {% else %} {% if is_login %}
        <a href="/login/redirect=&">
            <button class="hover:text-rose-500 duration-150">
                <i class="ti ti-login text-2xl"></i>
            </button>
        </a>
        {% endif %} {% if is_registration %}
        <a href="/signup">
            <button class="hover:text-rose-500 duration-150">
                <i class="ti ti-user-plus text-2xl"></i>
            </button>
        </a>
        {% endif %} {% endif %}
    </div>

    <script src="{{ url_for('static', filename='js/navbar.js') }}"></script>
</div>

app/templates/components/pagination.html
{% macro pagination(page, total_pages, base_url) %}
<div class="join flex justify-center mt-8">
    {% if page > 1 %}
    <a href="{{ base_url }}?page={{ page-1 }}" class="join-item btn btn-sm">Prev</a>
    {% endif %}
    <span class="join-item btn btn-sm pointer-events-none">{{ page }} / {{ total_pages }}</span>
    {% if page < total_pages %}
    <a href="{{ base_url }}?page={{ page+1 }}" class="join-item btn btn-sm">Next</a>
    {% endif %}
</div>
{% endmacro %}

app/templates/components/postCardMacro.html
{% macro postCard(post, author_profile_picture) %}
<div
    class="flex flex-col bg-base-200 rounded-box w-[20rem] h-[30rem] hover:scale-105 duration-150"
>
    <div class="overflow-hidden flex-shrink-0">
        <img
            src="{{ url_for('return_post_banner.return_post_banner', post_id=post[0]) }}"
            class="h-48 w-full group-hover:scale-110 transition duration-150 object-cover rounded-t-md select-none"
        />
    </div>
    <div class="flex flex-col gap-4 p-6 flex-grow">
        <h3 class="text-secondary font-medium text-sm line-clamp-1">
            {{ post[9] }}
        </h3>

        <a
                            href="{{ url_for('post.post', slug=get_slug_from_post_title(post[1]), url_id=post[10]) }}"
            class="link link-hover text-xl font-bold line-clamp-2 leading-tight"
            >{{ post[1] }}</a
        >

        <div class="overflow-hidden flex-grow">
            <span class="text-sm leading-relaxed line-clamp-4 break-words">
                {{ post[11] }}
            </span>
        </div>

        <div class="flex justify-between items-center mt-auto pt-2 w-full">
            <a
                href="/user/{{ post[5] }}"
                class="flex items-center gap-2 min-w-0"
            >
                <img
                    alt="Profile"
                    src="{{ author_profile_picture }}"
                    class="w-8 h-8 rounded object-cover flex-shrink-0"
                />
                <span class="font-medium text-sm truncate">{{ post[5] }}</span>
            </a>
            <span class="date text-sm flex-shrink-0">{{ post[7] }}</span>
        </div>
    </div>
</div>
{% endmacro %}

app/templates/components/sortMenu.html
{% macro sortMenu(sort_name,source,translations) %}
<div class="dropdown">
    <div
        tabindex="0"
        role="button"
        class="btn w-full md:w-fit text-base-content"
    >
        {{sort_name}}
    </div>
    <ul
        tabindex="0"
        class="dropdown-content menu bg-base-100 rounded-box z-1 w-full md:w-fit p-2 shadow-sm"
    >
        <li class="menu-title">{{ translations.sortMenu.desc }}</li>
        <li>
                            <a onclick="location = '{{source}}/by=time_stamp/sort=desc'">
                {{ translations.sortMenu.create }}
            </a>
        </li>
        <li>
            <a onclick="location = '{{source}}/by=title/sort=desc'">
                {{ translations.sortMenu.title }}
            </a>
        </li>
        <li>
            <a onclick="location = '{{source}}/by=views/sort=desc'">
                {{ translations.sortMenu.views }}
            </a>
        </li>
        <li>
            <a onclick="location = '{{source}}/by=category/sort=desc'">
                {{ translations.sortMenu.category }}
            </a>
        </li>
        <li>
                            <a onclick="location = '{{source}}/by=last_edit_time_stamp/sort=desc'">
                {{ translations.sortMenu.edit }}
            </a>
        </li>
        <li>
            <a onclick="location = '{{source}}/by=hot/sort=desc'">
                {{ translations.sortMenu.hot }}
            </a>
        </li>

        <li class="menu-title">{{ translations.sortMenu.asc }}</li>
        <li>
                            <a onclick="location = '{{source}}/by=time_stamp/sort=asc'">
                {{ translations.sortMenu.create }}
            </a>
        </li>
        <li>
            <a onclick="location = '{{source}}/by=title/sort=asc'">
                {{ translations.sortMenu.title }}
            </a>
        </li>
        <li>
            <a onclick="location = '{{source}}/by=views/sort=asc'">
                {{ translations.sortMenu.views }}
            </a>
        </li>
        <li>
            <a onclick="location = '{{source}}/by=category/sort=asc'">
                {{ translations.sortMenu.category }}
            </a>
        </li>
        <li>
                            <a onclick="location = '{{source}}/by=last_edit_time_stamp/sort=asc'">
                {{ translations.sortMenu.edit }}
            </a>
        </li>
        <li>
            <a onclick="location = '{{source}}/by=hot/sort=asc'">
                {{ translations.sortMenu.hot }}
            </a>
        </li>
    </ul>
</div>
{% endmacro %}