app/utils/forms/ChangePasswordForm.py
"""
This file contains class that are used to create ChangePasswordForm for the application.
"""

from wtforms import (
    Form,
    PasswordField,
    validators,
)


class ChangePasswordForm(Form):
    """
    This class creates a form for changing the password.
    """

    old_password = PasswordField(
        "old_password",
        [
            validators.Length(min=8),
            validators.InputRequired(),
        ],
    )

    password = PasswordField(
        "password",
        [
            validators.Length(min=8),
            validators.InputRequired(),
        ],
    )

    password_confirm = PasswordField(
        "password_confirm",
        [
            validators.Length(min=8),
            validators.InputRequired(),
        ],
    )

app/utils/forms/ChangeProfilePictureForm.py
"""
This file contains class that are used to create ChangeProfilePictureForm for the application.
"""

from wtforms import (
    Form,
    StringField,
    validators,
)


class ChangeProfilePictureForm(Form):
    """
    This class creates a form for changing the profile picture.
    """

    new_profile_picture_seed = StringField(
        "ProfilePictureSeed",
        [validators.InputRequired()],
    )

app/utils/forms/ChangeUserNameForm.py
"""
This file contains class that are used to create ChangeUserNameForm for the application.
"""

from wtforms import (
    Form,
    StringField,
    validators,
)


class ChangeUserNameForm(Form):
    """
    This class creates a form for changing the username.
    """

    new_username = StringField(
        "Username",
        [validators.Length(min=4, max=25), validators.InputRequired()],
    )

app/utils/forms/LoginForm.py
"""
This file contains class that are used to create LoginForm for the application.
"""

from wtforms import (
    Form,
    PasswordField,
    StringField,
    validators,
)


class LoginForm(Form):
    """
    This class creates a form for logging in.
    """

    username = StringField(
        "Username",
        [validators.Length(min=4, max=25), validators.InputRequired()],
    )

    password = PasswordField(
        "Password",
        [validators.Length(min=5), validators.InputRequired()],
    )

app/routes/about.py
"""
This module contains the about page blueprint.
"""

from flask import Blueprint, render_template
from settings import Settings
from utils.log import Log

about_blueprint = Blueprint("about", __name__)


@about_blueprint.route("/about")
def about():
    """
    This function is used to render the about page.

    :param app_name: The name of the application
    :type app_name: str
    :return: The rendered about page
    :rtype: flask.Response
    """

    Log.info(
        f"Rendering about.html: params: app_name={Settings.APP_NAME} and app_version={Settings.APP_VERSION}"
    )

    return render_template(
        "about.html", app_name=Settings.APP_NAME, app_version=Settings.APP_VERSION
    )

app/routes/account_settings.py
import sqlite3

from flask import Blueprint, redirect, render_template, request, session
from settings import Settings
from utils.delete import delete_user
from utils.log import Log

account_settings_blueprint = Blueprint("account_settings", __name__)


@account_settings_blueprint.route("/account_settings", methods=["GET", "POST"])
def account_settings():
    if "username" in session:
        Log.database(f"Connecting to '{Settings.DB_USERS_ROOT}' database")

        connection = sqlite3.connect(Settings.DB_USERS_ROOT)
        connection.set_trace_callback(Log.database)
        cursor = connection.cursor()
        cursor.execute(
            """select username from users where username = ? """,
            [(session["username"])],
        )
        user = cursor.fetchall()

        if request.method == "POST":
            delete_user(user[0][0])
            return redirect("/")

        return render_template(
            "accountSettings.html",
            user=user,
        )
    else:
        Log.error(
            f"{request.remote_addr} tried to reach account settings without being logged in"
        )

        return redirect("/login/redirect=&account_settings")

app/routes/admin_panel.py
import sqlite3

from flask import Blueprint, redirect, render_template, request, session
from settings import Settings
from utils.log import Log

admin_panel_blueprint = Blueprint("admin_panel", __name__)


@admin_panel_blueprint.route("/admin")
def admin_panel():
    if "username" in session:
        Log.success(f"Connecting to '{Settings.DB_USERS_ROOT}' database")

        connection = sqlite3.connect(Settings.DB_USERS_ROOT)
        connection.set_trace_callback(Log.database)
        cursor = connection.cursor()
        cursor.execute(
            """select role from users where username = ? """,
            [(session["username"])],
        )
        role = cursor.fetchone()[0]

        if role == "admin":
            Log.info(f"Admin: {session['username']} reached to the admin panel")

            Log.info("Rendering adminPanel.html: params: None")

            return render_template("adminPanel.html")
        else:
            Log.error(
                f"{request.remote_addr} tried to reach admin panel without being admin"
            )

            return redirect("/")
    else:
        Log.error(f"{request.remote_addr} tried to reach admin panel being logged in")

        return redirect("/")

app/routes/admin_panel_comments.py
from flask import (
    Blueprint,
    redirect,
    render_template,
    request,
    session,
)
from settings import Settings
from utils.log import Log
from utils.paginate import paginate_query

admin_panel_comments_blueprint = Blueprint("adminPanelComments", __name__)


@admin_panel_comments_blueprint.route("/admin/comments", methods=["GET", "POST"])
@admin_panel_comments_blueprint.route("/adminpanel/comments", methods=["GET", "POST"])
def admin_panel_comments():
    if "username" in session:
        Log.info(f"Admin: {session['username']} reached to comments admin panel")
        Log.database(f"Connecting to '{Settings.DB_COMMENTS_ROOT}' database")

        comments, page, total_pages = paginate_query(
            Settings.DB_COMMENTS_ROOT,
            "select count(*) from comments",
            "select * from comments order by time_stamp desc",
        )

        Log.info(f"Rendering adminPanelComments.html: params: comments={comments}")

        return render_template(
            "adminPanelComments.html",
            comments=comments,
            page=page,
            total_pages=total_pages,
        )
    else:
        Log.error(
            f"{request.remote_addr} tried to reach comment admin panel being logged in"
        )

        return redirect("/")

app/routes/admin_panel_users.py
import sqlite3

from flask import (
    Blueprint,
    redirect,
    render_template,
    request,
    session,
)
from settings import Settings
from utils.change_user_role import change_user_role
from utils.delete import delete_user
from utils.log import Log
from utils.paginate import paginate_query

admin_panel_users_blueprint = Blueprint("admin_panel_users", __name__)


@admin_panel_users_blueprint.route("/admin/users", methods=["GET", "POST"])
@admin_panel_users_blueprint.route("/admin_panel/users", methods=["GET", "POST"])
def admin_panel_users():
    if "username" in session:
        Log.info(f"Admin: {session['username']} reached to users admin panel")
        Log.database(f"Connecting to '{Settings.DB_USERS_ROOT}' database")

        connection = sqlite3.connect(Settings.DB_USERS_ROOT)
        connection.set_trace_callback(Log.database)
        cursor = connection.cursor()
        cursor.execute(
            """select role from users where username = ? """,
            [(session["username"])],
        )
        role = cursor.fetchone()[0]

        if request.method == "POST":
            if "user_delete_button" in request.form:
                Log.info(
                    f"Admin: {session['username']} deleted user: {request.form['username']}"
                )

                delete_user(request.form["username"])

            if "user_role_change_button" in request.form:
                Log.info(
                    f"Admin: {session['username']} changed {request.form['username']}'s role"
                )

                change_user_role(request.form["username"])

        if role == "admin":
            users, page, total_pages = paginate_query(
                Settings.DB_USERS_ROOT,
                "select count(*) from users",
                "select * from users",
            )

            Log.info(f"Rendering adminPanelUsers.html: params: users={users}")

            return render_template(
                "adminPanelUsers.html",
                users=users,
                page=page,
                total_pages=total_pages,
            )
        else:
            Log.error(
                f"{request.remote_addr} tried to reach user admin panel without being admin"
            )

            return redirect("/")
    else:
        Log.error(
            f"{request.remote_addr} tried to reach user admin panel being logged in"
        )

        return redirect("/")

app/routes/category.py
"""
This module contains the route for category pages.

DISCLAIMER: This code is the property of the repository owner and is not intended for
use without explicit permission from the owner. The code is provided as-is and is
subject to change without notice. Use of this code for commercial or non-commercial
purposes without permission is strictly prohibited.
"""

from json import load

from flask import Blueprint, abort, redirect, render_template, session
from settings import Settings
from utils.log import Log
from utils.paginate import paginate_query

category_blueprint = Blueprint("category", __name__)


@category_blueprint.route("/category/<category>")
@category_blueprint.route("/category/<category>/by=<by>/sort=<sort>")
def category(category, by="time_stamp", sort="desc"):
    """
    This function handles requests for the category route.

    :param category: The category name that is requested
    :param by: The field to sort the posts by
    :param sort: The sorting order of the posts
    :return: A rendered template with the posts and the category as context
    """

    categories = [
        "games",
        "history",
        "science",
        "code",
        "technology",
        "education",
        "sports",
        "foods",
        "health",
        "apps",
        "movies",
        "series",
        "travel",
        "books",
        "music",
        "nature",
        "art",
        "finance",
        "business",
        "web",
        "other",
    ]

    by_options = ["time_stamp", "title", "views", "category", "last_edit_time_stamp"]
    sort_options = ["asc", "desc"]

    if by not in by_options or sort not in sort_options:
        Log.warning(
            f"The provided sorting options are not valid: By: {by} Sort: {sort}"
        )
        return redirect(f"/category/{category}")

    if category.lower() not in categories:
        abort(404)

    posts, page, total_pages = paginate_query(
        Settings.DB_POSTS_ROOT,
        "select count(*) from posts where lower(category) = ?",
        f"select * from posts where lower(category) = ? order by {by} {sort}",
        [category.lower()],
    )

    if by == "time_stamp":
        by = "create"
    elif by == "last_edit_time_stamp":
        by = "edit"

    language = session.get("language")
    translation_file = f"./translations/{language}.json"
    with open(translation_file, "r", encoding="utf-8") as file:
        translations = load(file)

    sort_name = translations["sortMenu"][by] + " - " + translations["sortMenu"][sort]

    Log.info(f"Sorting posts on category/{category} page by: {sort_name}")

    return render_template(
        "category.html",
        posts=posts,
        category=translations["categories"][category.lower()],
        sort_name=sort_name,
        source=f"/category/{category}",
        page=page,
        total_pages=total_pages,
    )

app/routes/change_language.py
from flask import Blueprint, redirect, request, session

change_language_blueprint = Blueprint("change_language", __name__)


@change_language_blueprint.route("/change_language", methods=["GET", "POST"])
def change_language():
    """
    This function is the route for the change language page.
    It is used to change the user's language.

    Args:
        request.form (dict): the form data from the request

    Returns:
        redirect: a redirect to the previous page
    """

    if request.method == "POST":
        language = request.form["language"]
        session["language"] = language
        return redirect(request.form["redirect"])

    return redirect("/")

app/routes/change_password.py
import sqlite3

from flask import (
    Blueprint,
    redirect,
    render_template,
    request,
    session,
)
from passlib.hash import sha512_crypt as encryption
from settings import Settings
from utils.flash_message import flash_message
from utils.forms.ChangePasswordForm import ChangePasswordForm
from utils.log import Log

change_password_blueprint = Blueprint("change_password", __name__)


@change_password_blueprint.route("/change_password", methods=["GET", "POST"])
def change_password():
    """
    This function is the route for the change password page.
    It is used to change the user's password.

    Args:
        request.form (dict): the form data from the request

    Returns:
        render_template: a rendered template with the form
    """

    if "username" in session:
        form = ChangePasswordForm(request.form)

        if request.method == "POST":
            old_password = request.form["old_password"]
            password = request.form["password"]
            password_confirm = request.form["password_confirm"]
            Log.database(f"Connecting to '{Settings.DB_USERS_ROOT}' database")

            connection = sqlite3.connect(Settings.DB_USERS_ROOT)
            connection.set_trace_callback(Log.database)
            cursor = connection.cursor()

            cursor.execute(
                """select password from users where username = ? """,
                [(session["username"])],
            )

            if encryption.verify(old_password, cursor.fetchone()[0]):
                if old_password == password:
                    flash_message(
                        page="change_password",
                        message="same",
                        category="error",
                        language=session["language"],
                    )

                if password != password_confirm:
                    flash_message(
                        page="change_password",
                        message="match",
                        category="error",
                        language=session["language"],
                    )

                if old_password != password and password == password_confirm:
                    new_password = encryption.hash(password)
                    Log.database(f"Connecting to '{Settings.DB_USERS_ROOT}' database")

                    connection = sqlite3.connect(Settings.DB_USERS_ROOT)
                    connection.set_trace_callback(Log.database)
                    cursor = connection.cursor()
                    cursor.execute(
                        """update users set password = ? where username = ? """,
                        [(new_password), (session["username"])],
                    )

                    connection.commit()

                    Log.success(
                        f'User: "{session["username"]}" changed his password',
                    )

                    session.clear()
                    flash_message(
                        page="change_password",
                        message="success",
                        category="success",
                        language=session["language"],
                    )

                    return redirect("/login/redirect=&")
            else:
                flash_message(
                    page="change_password",
                    message="old",
                    category="error",
                    language=session["language"],
                )

        return render_template(
            "changePassword.html",
            form=form,
        )
    else:
        Log.error(
            f"{request.remote_addr} tried to change his password without logging in"
        )
        flash_message(
            page="change_password",
            message="login",
            category="error",
            language=session["language"],
        )

        return redirect("/login/redirect=change_password")

app/routes/return_post_banner.py
import sqlite3
from io import BytesIO

from flask import Blueprint, request, send_file
from settings import Settings
from utils.log import Log

return_post_banner_blueprint = Blueprint("return_post_banner", __name__)


@return_post_banner_blueprint.route("/post_image/<int:post_id>")
def return_post_banner(post_id):
    """
    This function returns the banner image for a given post ID.

    Args:
        post_id (int): The ID of the post for which the banner image is requested.

    Returns:
        The banner image for the given post ID as a Flask Response object.

    """
    Log.database(f"Connecting to '{Settings.DB_POSTS_ROOT}' database")

    connection = sqlite3.connect(Settings.DB_POSTS_ROOT)
    connection.set_trace_callback(Log.database)

    cursor = connection.cursor()

    cursor.execute(
        """select banner from posts where id = ? """,
        [(post_id)],
    )

    image = BytesIO(cursor.fetchone()[0])

    Log.info(f"Post: {post_id} | Image: {request.base_url} loaded")

    return send_file(image, mimetype="image/png")

app/templates/dashboard.html
{% extends 'layout.html' %} {% block head %} {% if request.path ==
"/admin/posts" %}
<title>{{translations.dashboard.titleAdmin}}</title>
{% else %}
<title>{{translations.dashboard.title}}</title>
{% endif %} {% endblock head %} {% block body %} {% if show_posts %}
<h1 class="my-4 text-4xl font-medium select-none text-center">
    {{translations.dashboard.posts}}
</h1>

{% for post in posts %}
<div
    class="w-11/12 md:w-10/12 lg:w-8/12 xl:w-5/12 h-fit mx-auto py-4 px-2 my-8 border-2 rounded-md shadow-md border-gray-500/25"
>
    <img
        src="{{ url_for('return_post_banner.return_post_banner', post_id= post[0]) }}"
        class="w-96 rounded mx-auto"
    />

    <a
        href="/post/{{ post[10] }}"
        class="text-rose-500 h-64 pb-8 text-2xl hover:text-rose-500/75 duration-150 select-none break-words"
        >{{ post[1] }}</a
    >

    <div
        tag="content"
        class="h-60 overflow-y-hidden mt-6 mb-3 break-words markdown-content compact"
    >
        {{ render_markdown(post[3]) }}
    </div>

    <section class="flex items-center justify-between my-2">
        <a
            href="/edit_post/{{ post[10] }}"
            class="hover:text-rose-500 duration-150 font-medium"
        >
            <i class="ti ti-edit mr-1 text-2xl"></i>
        </a>
        <form method="post">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            <input type="hidden" name="post_id" value="{{ post[0] }}" />
            <button
                type="submit"
                name="post_delete_button"
                class="hover:text-rose-500 duration-150 font-medium"
            >
                <i class="ti ti-trash-x mr-1 text-2xl"></i>
            </button>
        </form>
    </section>

    <div class="flex items-center justify-between my-2">
        <div class="flex items-center">
            <i class="ti ti-tags mr-1 text-xl"></i>
            <p class="hidden md:block mr-1">{{translations.dashboard.tags}}:</p>
            <p class="font-medium">{{ post[2] }}</p>
        </div>
        <div class="flex items-center">
            <i class="ti ti-eye mr-1 text-xl"></i>
            <p class="hidden md:block mr-1">
                {{translations.dashboard.views}}:
            </p>
            <p class="font-medium">{{ post[6] }}</p>
        </div>
    </div>

    <div class="flex items-center justify-between my-2">
        <div class="flex items-center">
            <i class="ti ti-clock mr-1 text-xl"></i>
            <p class="hidden md:block mr-1">
                {{translations.dashboard.creationTime}}:
            </p>
            <p class="time font-medium">{{ post[7] }}</p>
        </div>
        <div class="flex items-center">
            <i class="ti ti-clock-edit mr-1 text-xl"></i>
            <p class="hidden md:block mr-1">
                {{translations.dashboard.editTime}}:
            </p>
            <p class="time font-medium">{{ post[8] }}</p>
        </div>
    </div>

    <div class="flex items-center justify-between my-2">
        <div class="flex items-center">
            <i class="ti ti-calendar mr-1 text-xl"></i>
            <p class="hidden md:block mr-1">
                {{translations.dashboard.creationDate}}:
            </p>
            <p class="date font-medium">{{ post[7] }}</p>
        </div>
        <div class="flex items-center">
            <i class="ti ti-calendar-dot mr-1 text-xl"></i>
            <p class="hidden md:block mr-1">
                {{translations.dashboard.editDate}}:
            </p>
            <p class="date font-medium">{{ post[8] }}</p>
        </div>
    </div>

    <div class="flex items-center justify-between my-2">
        {% if request.path == "/admin/posts" %}
        <div class="flex items-center">
            <i class="ti ti-user mr-1 text-xl"></i>
            <p class="hidden md:block mr-1">
                {{translations.dashboard.author}}:
            </p>
            <a
                href="/user/{{ post[5].lower() }}"
                class="hover:text-rose-500 duration-150 font-medium"
                >{{ post[5] }}</a
            >
        </div>
        {% endif %}
        <div class="flex items-center">
            <i class="ti ti-category mr-1 text-xl"></i>
            <p class="hidden md:block mr-1">
                {{translations.dashboard.category}}:
            </p>
            <p class="font-medium">{{ post[9] }}</p>
        </div>
    </div>
</div>
{% endfor %} {% from "components/pagination.html" import pagination %} {{
pagination(page, total_pages, request.path) }} {% elif not show_posts %} {% if
request.path == "/admin/posts" %}
<h1>{{translations.dashboard.noPosts}}</h1>
{% else %}
<p class="text-center mt-32 select-none">
    {{translations.dashboard.noPost}}
    <a href="/create_post" class="hover:text-rose-500 duration-150 font-medium"
        >{{translations.dashboard.create}}</a
    >?
</p>
{% endif %} {% endif %} {% if show_comments and not request.path ==
"/admin/posts" %}
<h1 class="my-4 text-4xl font-medium select-none text-center">
    {{translations.dashboard.comments}}
</h1>

{% for comment in comments %}
<div
    class="w-11/12 md:w-10/12 lg:w-3/4 xl:w-1/2 h-fit mx-auto py-4 px-2 my-8 border-2 rounded-md shadow-md border-gray-500/25"
>
    <div tag="content">{{ comment[2] | e }}</div>

    <section class="flex items-center justify-between my-2">
        <div class="flex items-center">
            <i class="ti ti-calendar mr-1 text-xl"></i>
            <p class="hidden md:block mr-1">
                {{translations.dashboard.creationDate}}:
            </p>
            <p class="date">{{ comment[4] }}</p>
        </div>
        <div class="flex items-center">
            <i class="ti ti-clock mr-1 text-xl"></i>
            <p class="hidden md:block mr-1">
                {{translations.dashboard.creationTime}}:
            </p>
            <p class="time">{{ comment[4] }}</p>
        </div>
    </section>

    <a
        href="/post/{{ getPostUrlIdFromPost(comment[1]) }}"
        class="hover:text-rose-500 duration-150 font-medium"
        >{{translations.dashboard.go}}</a
    >
</div>
{% endfor %} {% endif %} {% if request.path == "/admin/posts" %}
<a href="/admin" class="hidden md:block fixed bottom-0 left-1">
    <i
        class="ti ti-arrow-back mr-1 text-xl hover:text-rose-500 duration-150"
    ></i>
</a>
{% else %}
<a
    href='/user/{{ session["username"] }}'
    class="hidden md:block fixed bottom-0 left-1"
>
    <i
        class="ti ti-arrow-back mr-1 text-xl hover:text-rose-500 duration-150"
    ></i>
</a>
{% endif %} {% endblock body %}

app/templates/post.html
{% extends 'layout.html' %} {% block head %}
<title>{{ title }}</title>

<meta property="og:type" content="article" />
<meta property="og:title" content="{{ title }}" />
<meta
    property="og:image"
    content="{{
    blogPostUrl
  }}{{ url_for('return_post_banner.return_post_banner', post_id= id) }}"
/>
<meta name="keywords" content="{{ tags }}" />
<meta name="author" content="{{ author }}" />
<meta property="og:url" content="{{ blogPostUrl }}" />
<meta property="og:description" content="{{ abstract | striptags + '...' }}" />
<meta name="twitter:site" content="{{ appName }}" />
<meta name="twitter:title" content="{{ title }}" />
<meta name="twitter:description" content="{{ abstract | striptags + '...' }}" />
<meta
    name="twitter:image"
    content="{{
    blogPostUrl
  }}{{ url_for('return_post_banner.return_post_banner', post_id= id) }}"
/>
<meta property="og:site_name" content="{{ appName }}" />

{% endblock head %} {% block body %}
<script>
    let visitorID = parseInt("{{ idForRandomVisitor | safe }}");
    const csrfToken = "{{ csrf_token() }}";
</script>
<div
    class="w-11/12 md:w-5/6 lg:w-7/12 xl:w-5/12 mx-auto mt-6 md:mt-10 break-words"
>
    <img
        src="{{ url_for('return_post_banner.return_post_banner', post_id= id) }}"
        class="mx-auto rounded-md shadow-md select-none"
    />

    <h1
        class="text-2xl md:text-3xl mt-3 text-rose-500 w-full text-center font-bold"
    >
        {{ title }}
    </h1>

    <div
        class="flex items-center justify-center gap-2 my-4 select-none opacity-75"
    >
        <p class="text-sm font-medium">
            {{ readingTime|string + " " + translations.post.minRead }}
        </p>
        {% if author == session["username"] or "admin" == session["username"] %}
        <a
            href="/analytics/posts/{{ url_id }}"
            class="shadow-lg hover:text-rose-500 duration-150"
            >{{ translations.post.viewPerformance }}</a
        >
        {% endif %}
    </div>

    <div class="text-center font-sm max-w-full">{{ abstract }}</div>

    <div class="divider"></div>

    <div class="markdown-content">{{ render_markdown(content) }}</div>

    <div class="select-none">
        <div class="flex w-full justify-between my-1">
            <div class="flex items-center">
                <i class="ti ti-tags mr-1 text-2xl"></i>
                {{ tags.replace(",", ", ") }}
            </div>
            <a
                target="_blank"
                href="https://x.com/intent/tweet?text={{ title }} by {{ author }} on {{
          appName
        }} {{ request.base_url }}"
            >
                <i
                    class="hover:text-rose-500 duration-150 ti ti-brand-x text-2xl"
                ></i>
            </a>
        </div>

        <div class="flex w-full justify-between my-1">
            <h5>
                <div class="flex items-center">
                    <i class="ti ti-eye mr-1 text-2xl"></i>
                    {{ views }}
                </div>
            </h5>
            <h5 class="time">{{ time_stamp }}</h5>
        </div>

        <div class="flex w-full justify-between my-1">
            <a
                href="/user/{{ author | lower }}"
                class="hover:text-rose-500 duration-150"
            >
                <h5 class="m-1 flex">
                    <img
                        class="w-7 mr-2 select-none"
                        src="{{ get_profile_picture(author) }}"
                        alt="{{ author }}"
                    />
                    {{ author }}
                </h5>
            </a>
            <h5 class="date">{{ time_stamp }}</h5>
        </div>
    </div>

    {% if author == session["username"] %}
    <div class="flex justify-between px-2">
        <form method="post">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            <button
                type="submit"
                name="post_delete_button"
                class="text-rose-500 hover:text-rose-500/75 duration-150"
            >
                <i class="ti ti-trash-x mr-1 text-2xl"></i>
            </button>
        </form>
        <a
            href="/edit_post/{{ url_id }}"
            class="text-rose-500 hover:text-rose-500/75 duration-150"
        >
            <i class="ti ti-edit mr-1 text-2xl"></i>
        </a>
    </div>
    {% endif %}

    <div>
        {% for comment in comments %}
        <div class="flex flex-col mx-auto mt-8 mb-4 p-2 max-w-lg">
            <div class="flex w-full justify-between">
                <div class="mx-2">
                    <a
                        href="/user/{{ comment[3] }}"
                        class="flex items-center hover:text-rose-500 duration-150 select-none"
                    >
                        <img
                            class="w-7 mr-2"
                            src="{{ get_profile_picture(comment[3]) }}"
                            alt=""
                        />
                        <div>{{ comment[3] }}</div>
                    </a>
                </div>
                {% if session["username"] == comment[3] %}
                <form method="post" class="mx-2 my-1">
                    <input
                        type="hidden"
                        name="csrf_token"
                        value="{{ csrf_token() }}"
                    />
                    <input
                        type="hidden"
                        name="commentID"
                        value="{{ comment[0] }}"
                    />
                    <button
                        type="submit"
                        name="commentDeleteButton"
                        class="hover:text-rose-500 duration-150"
                    >
                        <i class="ti ti-trash-x mr-1 text-xl"></i>
                    </button>
                </form>
                {% endif %}
            </div>
            <p class="break-words ml-8">
                <i
                    class="ti ti-corner-down-right mr-1 text-xl inline-block"
                ></i>
                {{ comment[2] | e }}
            </p>
        </div>
        {% endfor %}
    </div>
</div>
<div class="mx-auto text-center my-8 w-10/12 md:w-5/12 lg:w-4/12 xl:w-3/12">
    <form method="post" class="md:w-max">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
        {% if session["username"] %}
        <div class="border rounded border-rose-500/25">
            {{ form.comment(class_="textarea textarea-bordered w-full h-24
            my-2",placeholder=translations.post.placeholder) }}
            <button type="submit" class="btn btn-neutral mt-2">
                <i class="ti ti-arrow-narrow-up mr-1 text-xl"></i>
            </button>
        </div>
    </form>
    {% endif %}
</div>

<script src="{{ url_for('static', filename='js/post.js') }}"></script>
{% endblock body %}

app/templates/unauthorized.html
{% extends 'layout.html' %} {% block head %}
<title>{{translations.verifyAccount.title}}</title>
{% endblock head %} {% block body %}
<div class="w-fit mx-auto mt-32 text-2xl text-center font-medium select-none">
    <h1>{{translations.verifyAccount.info}}</h1>
    <h1>{{translations.verifyAccount.request}}</h1>
</div>
{% endblock body %}